### PR TITLE
Remove notifications fix

### PR DESCRIPTION
**Pull request by DevAlien**
Hi,
I've added a couple of features.

First of all I made that when you remove a notification it actually disappears from the dom, it gets delete from the `notifications` array. This is needed because if an app is running for hours then you could have thousands notifications in background, in your DOM, which is not good.

The second thing I've added is a way to click the notification, or disable the clicking, since I noticed that the list was not disabled so it seemed you could click it.
Instead of that I did that if you pass an `onClick` it will be clicked and once you click the notification will also disappear while if you don't pass an onClick the list will be disabled so it won't look like you can click on it.

### CODE REVIEW

**Comment by puranjayjain** [comment]
@DevAlien wow 😆 that was fast I'll review these changes and make a release with them

**Comment by puranjayjain** [comment]
on an initial read seems fine will test and get back to you on this 🥂

**Comment by DevAlien** [comment]
@puranjayjain is this released on npm?

**Comment by puranjayjain** [comment]
its not released yet.

**Pull request merged**
